package AdditionCorrugated.MCEconomy2;

import net.minecraft.item.*;
import shift.mceconomy2.api.*;
import cpw.mods.fml.common.Mod.*;
import cpw.mods.fml.common.event.*;
import AdditionCorrugated.*;

public class Price
{
	@EventHandler
	public void init(FMLPostInitializationEvent event)
	{
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.Corrugated), 10);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.ACrecycle), 100);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.Adamantite), 50);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.AdamantiteAxe), 55);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.AdamantiteHoe), 55);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.AdamantitePickaxe), 55);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.AdamantiteShovel), 55);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.AdamantiteSword), 55);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.BlackStone), 2);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.Blueberry), 5);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.Capsicum), 2);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.ChocolateBar), 10);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.Cobalt), 60);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.CobaltAxe), 65);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.CobaltHoe), 65);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.CobaltPickaxe), 65);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.CobaltShovel), 65);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.CobaltSword), 65);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.CorrugatedAxe), 15);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.TStone), 1);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.CorrugatedBoard), 5);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.CorrugatedChest), 15);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.CorrugatedHoe), 15);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.CorrugatedLight),20);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.CorrugatedPickaxe), 15);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.CorrugatedShovel), 15);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.CorrugatedSword), 15);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.CorrugatedTorch), 15);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.Cutter), 50);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.TemperedGlass), 100);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.Demonite), 100);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.DemoniteAxe), 105);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.DemoniteHoe), 105);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.DemonitePickaxe), 105);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.DemoniteShovel), 105);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.DemoniteSword), 105);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.DrySpongeGourd), 105);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.Dumpling), 5);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.Edge), 150);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.FermentedSoybeans), 50);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.Fluorite), 100);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.GlutinousRice), 10);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.GoldGravel), 50);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.Gum), 5);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.JapaneseLeek), 15);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.Kimchi), 35);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.HalfCorrugated), 5);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.HalfCorrugatedLight), 5);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.HalfStrongCorrugated), 5);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.HalfStrongCorrugatedLight), 5);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.Hellstone), 70);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.HellstoneAxe), 75);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.HellstoneHoe), 75);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.HellstonePickaxe), 75);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.HellstoneShovel), 75);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.HellstoneSword), 75);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.Mythril), 80);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.MythrilAxe), 85);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.MythrilHoe), 85);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.MythrilPickaxe), 85);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.MythrilShovel), 85);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.MythrilSword), 85);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.Meteorite), 40);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.MeteoriteAxe), 45);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.MeteoriteHoe), 45);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.MeteoritePickaxe), 45);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.MeteoriteShovel), 45);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.MeteoriteSword), 45);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.Mustard), 5);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.MintGum), 15);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.PickledPlum), 50);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.Plum), 15);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.PolishngPowder), 45);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.Rice), 8);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.RiceCake), 100);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.RustyEdge), 0);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.oreAdamantite), 50);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.oreCobalt), 50);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.oreDemonite), 50);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.oreFluorite), 50);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.oreHellstone), 50);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.oreMeteorite), 50);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.oreMythril), 50);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.oreSilver), 50);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.oreTNT), 50);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.SeaMustard), 65);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.SeaMustardRevision), 75);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.Silver), 1000);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.SilverGravel), 105);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.SolarFragment), 65);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.Spawn_Egg_CorrugatedCreeper), 0);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.Soybeans), 5);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.SoySauce), 5);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.SpongeGourd), 50);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.Star), 10);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.StarGravel), 15);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.Straw), 25);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.SuperMintGum), 45);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.StrongPaper), 10);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.StrongCorrugated), 20);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.StrongCorrugatedAxe), 25);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.StrongCorrugatedBoard), 2);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.StrongCorrugatedChest), 30);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.StrongCorrugatedHoe), 25);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.StrongCorrugatedLight), 20);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.StrongCorrugatedPickaxe), 25);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.StrongCorrugatedShovel), 25);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.StrongCorrugatedSword), 25);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.StrongCorrugatedTorch), 10);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.StrongRecycledPaper), 15);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.RecycledPaper), 2);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.StrongRecycledCorrugated), 75);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.RecycledCorrugated), 50);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.StrongRecycledCorrugatedBoard), 10);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.RecycledCorrugatedBoard), 5);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.StrongRecycledCorrugatedLight), 200);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugatedCore.RecycledCorrugatedLight), 150);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.CraftingEX.Blocks.Corrugated2), 10);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.CraftingEX.Blocks.CorrugatedLight2), 50);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.CraftingEX.Blocks.RecycledCorrugated2), 100);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.CraftingEX.Blocks.RecycledCorrugatedLight2), 150);
		MCEconomyAPI.ShopManager.addPurchaseEntity(AdditionCorrugated.Entity.EntityCorrugatedCreeper.class, 10);
	}
}