package AdditionCorrugated.MCEconomy2;

import net.minecraft.item.*;
import shift.mceconomy2.api.*;
import cpw.mods.fml.common.Mod.*;
import cpw.mods.fml.common.event.*;
import AdditionCorrugated.*;
import AdditionCorrugated.CraftingEX.*;

public class Price
{
	@EventHandler
	public void init(FMLPostInitializationEvent event)
	{
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Block.Blocks.Corrugated), 10);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Block.Blocks.ACrecycle), 100);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Block.Blocks.BlackStone), 2);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Block.Blocks.CorrugatedChest), 15);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Block.Blocks.CorrugatedLight),20);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Block.Blocks.TemperedGlass), 100);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Block.Blocks.CorrugatedTorch), 15);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Block.Blocks.HalfCorrugated), 5);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Block.Blocks.HalfCorrugatedLight), 5);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Block.Blocks.HalfStrongCorrugated), 5);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Block.Blocks.HalfStrongCorrugatedLight), 5);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Block.Blocks.GoldGravel), 50);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Block.Blocks.StarGravel), 15);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Block.Blocks.StrongCorrugated), 20);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Block.Blocks.StrongCorrugatedChest), 30);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Block.Blocks.StrongCorrugatedLight), 20);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Block.Blocks.StrongCorrugatedTorch), 10);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Block.Blocks.StrongRecycledCorrugated), 75);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Block.Blocks.RecycledCorrugated), 50);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Block.Blocks.StrongRecycledCorrugatedLight), 200);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Block.Blocks.RecycledCorrugatedLight), 150);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Block.Blocks.SilverGravel), 105);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Block.Blocks.oreAdamantite), 50);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Block.Blocks.oreCobalt), 50);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Block.Blocks.oreDemonite), 50);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Block.Blocks.oreFluorite), 50);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Block.Blocks.oreHellstone), 50);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Block.Blocks.oreMeteorite), 50);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Block.Blocks.oreMythril), 50);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Block.Blocks.oreSilver), 50);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.TNTRevolution.Block.Blocks.oreTNT), 50);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.TNTRevolution.Block.Blocks.TStone), 1);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.CraftingEX.Block.Blocks.Corrugated2), 10);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.CraftingEX.Block.Blocks.CorrugatedLight2), 50);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.CraftingEX.Block.Blocks.RecycledCorrugated2), 100);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.CraftingEX.Block.Blocks.RecycledCorrugatedLight2), 150);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.MCEconomy2.Block.Blocks.ACVendingMachine), 500);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Item.Items.CorrugatedAxe), 15);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Item.Items.CorrugatedBoard), 5);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Item.Items.CorrugatedHoe), 15);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Item.Items.CorrugatedPickaxe), 15);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Item.Items.CorrugatedShovel), 15);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Item.Items.CorrugatedSword), 15);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Item.Items.Cutter), 50);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Item.Items.Edge), 150);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Item.Items.PolishngPowder), 45);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Item.Items.RustyEdge), 0);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Item.Items.Spawn_Egg_CorrugatedCreeper), 0);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Item.Items.Star), 10);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Item.Items.StrongPaper), 10);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Item.Items.StrongCorrugatedAxe), 25);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Item.Items.StrongCorrugatedBoard), 2);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Item.Items.StrongCorrugatedHoe), 25);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Item.Items.StrongCorrugatedPickaxe), 25);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Item.Items.StrongCorrugatedShovel), 25);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Item.Items.StrongCorrugatedSword), 25);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Item.Items.StrongRecycledPaper), 15);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Item.Items.RecycledPaper), 2);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Item.Items.StrongRecycledCorrugatedBoard), 10);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.Item.Items.RecycledCorrugatedBoard), 5);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.Silver), 1000);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.Hellstone), 70);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.HellstoneAxe), 75);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.HellstoneHoe), 75);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.HellstonePickaxe), 75);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.HellstoneShovel), 75);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.HellstoneSword), 75);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.Mythril), 80);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.MythrilAxe), 85);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.MythrilHoe), 85);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.MythrilPickaxe), 85);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.MythrilShovel), 85);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.MythrilSword), 85);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.Meteorite), 40);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.MeteoriteAxe), 45);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.MeteoriteHoe), 45);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.MeteoritePickaxe), 45);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.MeteoriteShovel), 45);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.MeteoriteSword), 45);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.Fluorite), 100);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.Cobalt), 60);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.CobaltAxe), 65);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.CobaltHoe), 65);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.CobaltPickaxe), 65);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.CobaltShovel), 65);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.CobaltSword), 65);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.Adamantite), 50);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.AdamantiteAxe), 55);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.AdamantiteHoe), 55);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.AdamantitePickaxe), 55);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.AdamantiteShovel), 55);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.AdamantiteSword), 55);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.Demonite), 100);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.DemoniteAxe), 105);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.DemoniteHoe), 105);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.DemonitePickaxe), 105);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.DemoniteShovel), 105);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACOre.Item.Items.DemoniteSword), 105);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACFood.Item.Items.Rice), 8);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACFood.Item.Items.RiceCake), 100);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACFood.Item.Items.FermentedSoybeans), 50);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACFood.Item.Items.GlutinousRice), 10);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACFood.Item.Items.Gum), 5);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACFood.Item.Items.JapaneseLeek), 15);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACFood.Item.Items.Kimchi), 35);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACFood.Item.Items.Mustard), 5);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACFood.Item.Items.MintGum), 15);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACFood.Item.Items.PickledPlum), 50);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACFood.Item.Items.Plum), 15);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACFood.Item.Items.DrySpongeGourd), 105);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACFood.Item.Items.Dumpling), 5);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACFood.Item.Items.Blueberry), 5);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACFood.Item.Items.Capsicum), 2);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACFood.Item.Items.ChocolateBar), 10);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACFood.Item.Items.SeaMustard), 65);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACFood.Item.Items.SeaMustardRevision), 75);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACFood.Item.Items.SolarFragment), 65);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACFood.Item.Items.Soybeans), 5);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACFood.Item.Items.SoySauce), 5);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACFood.Item.Items.SpongeGourd), 50);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACFood.Item.Items.Straw), 25);
		MCEconomyAPI.ShopManager.addPurchaseItem(new ItemStack(AdditionCorrugated.ACFood.Item.Items.SuperMintGum), 45);
		MCEconomyAPI.ShopManager.addPurchaseEntity(AdditionCorrugated.Entity.EntityCorrugatedCreeper.class, 10);
	}
}